INSERT INTO ORDER_ITEMS (PRODUCT_NAME,PRODUCT_CODE,QUANTITY) values ('natural oil','111',2);
INSERT INTO ORDER_ITEMS (PRODUCT_NAME,PRODUCT_CODE,QUANTITY) values ('soap','121',3);
INSERT INTO ORDER_ITEMS (PRODUCT_NAME,PRODUCT_CODE,QUANTITY) values ('coconut','133',1);
