INSERT into ORDER_DETAIL (CUSTOMER_NAME,ORDER_DATE,SHIPPING_ADDRESS,TOTAL) values('abhay',sysdate,'bedok','30.55');
INSERT into ORDER_DETAIL (CUSTOMER_NAME,ORDER_DATE,SHIPPING_ADDRESS,TOTAL) values('amit',sysdate,'bedok','310.55');
INSERT into ORDER_DETAIL (CUSTOMER_NAME,ORDER_DATE,SHIPPING_ADDRESS,TOTAL) values('anita',sysdate,'bedok','430.55');