CREATE TABLE ORDER_DETAIL (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(250) NOT NULL,
  ORDER_DATE DATE NOT NULL,
  SHIPPING_ADDRESS VARCHAR(250) NOT NULL,
  TOTAL DECIMAL(6,2) NOT NULL
);